# Generated by Django 5.0 on 2024-01-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='body',
            field=models.TextField(default='text_message'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='subject',
            field=models.CharField(default='subject_message', max_length=255),
            preserve_default=False,
        ),
    ]
